/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutriologo;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ale
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menuu
     */
    public Menu() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("../Imagenes/hw.jpg")).getImage());
        this.setTitle("Monitoreo nutricional");
        this.getContentPane().setBackground(new Color(179, 217, 255));
        this.setSize(1300, 900);
        this.setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(255,255,255)); 
        //Funcion agregar
        lbTituloAgregar.setVisible(false);
        lbInstruccionesAgregar.setVisible(false);
        lbNombre.setVisible(false);
        lbAP.setVisible(false);
        lbAM.setVisible(false);
        lbSexo.setVisible(false);
        lbEdad.setVisible(false);
        lbPeso.setVisible(false);
        lbkg.setVisible(false);
        lbAltura.setVisible(false);
        lbcm.setVisible(false);
        lbUsuario.setVisible(false);
        lbContrasena.setVisible(false);
        txtNombre.setVisible(false);
        txtAP.setVisible(false);
        txtAM.setVisible(false);
        cmbSexo.setVisible(false);
        txtEdad.setVisible(false);
        txtPeso.setVisible(false);
        txtAltura.setVisible(false);
        txtUsuario.setVisible(false);
        pswContrasena.setVisible(false);
        btnAgregar.setVisible(false);
        btnCancelar.setVisible(false);
        //Funcion Modificar
        lbTituloModificar.setVisible(false);
        lbInstruccionesModificar.setVisible(false);
        btnGuardar.setVisible(false);
        //Funcion Ver
        lbTituloVer.setVisible(false);
        lbInstruccionesVer.setVisible(false);
        btnBuscar.setVisible(false);
        //Funcion Eliminar
        lbTituloEliminar.setVisible(false);
        lbInstruccionesEliminar.setVisible(false);
        btnEliminar.setVisible(false);
        //ACP
        lbPCA.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbTituloAgregar = new javax.swing.JLabel();
        lbInstruccionesAgregar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbAP = new javax.swing.JLabel();
        txtAP = new javax.swing.JTextField();
        lbAM = new javax.swing.JLabel();
        txtAM = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        lbAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lbcm = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lbEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbContrasena = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbkg = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        pswContrasena = new javax.swing.JPasswordField();
        lbInstruccionesModificar = new javax.swing.JLabel();
        lbTituloModificar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lbTituloVer = new javax.swing.JLabel();
        lbInstruccionesVer = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lbTituloEliminar = new javax.swing.JLabel();
        lbInstruccionesEliminar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lbPCA = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 427));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbNombre.setText("Nombre: ");

        lbTituloAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTituloAgregar.setText("Agregar un nuevo paciente");

        lbInstruccionesAgregar.setText("Ingrese los datos solicitados y presione el botón 'Agregar'.");

        lbAP.setText("Apellido paterno:");

        lbAM.setText("Apellido materno:");

        lbSexo.setText("Sexo:");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        lbAltura.setText("Altura:");

        lbcm.setText("cm");

        lbPeso.setText("Peso:");

        lbEdad.setText("Edad:");

        lbUsuario.setText("Usuario:");

        lbContrasena.setText("Contraseña:");

        btnAgregar.setText("Agregar");

        btnCancelar.setText("Cancelar");

        lbkg.setText("kg");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbInstruccionesModificar.setText("Busque al paciente, luego actualice los datos y presione el botón 'Guardar'.");

        lbTituloModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTituloModificar.setText("Modificar paciente");

        btnGuardar.setText("Guardar");

        lbTituloVer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTituloVer.setText("Ver paciente");

        lbInstruccionesVer.setText("Ingrese el nombre y apellidos del paciente y presione el botón 'Buscar'.");

        btnBuscar.setText("Buscar");

        lbTituloEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTituloEliminar.setText("Eliminar paciente");

        lbInstruccionesEliminar.setText("Busque por nombre y apellidos al paciente y presione el botón 'Borrar'.");

        btnEliminar.setText("Borrar");

        lbPCA.setBackground(new java.awt.Color(0, 0, 0));
        lbPCA.setIcon(new javax.swing.ImageIcon("C:\\Users\\aleja\\Documents\\UPIITA\\Proyecto_Terminal\\PT_I\\PCA.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTituloEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTituloVer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTituloModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTituloAgregar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbAP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbAM)
                                            .addComponent(lbSexo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbPeso, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lbAltura)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(txtPeso)
                            .addComponent(txtAltura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbkg)
                            .addComponent(lbcm))
                        .addGap(21, 21, 21))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbContrasena)
                            .addComponent(lbUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(pswContrasena))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addGap(56, 56, 56)
                        .addComponent(btnCancelar)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbInstruccionesEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInstruccionesVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInstruccionesAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInstruccionesModificar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbPCA)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloAgregar)
                    .addComponent(lbTituloModificar)
                    .addComponent(lbTituloVer)
                    .addComponent(lbTituloEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInstruccionesAgregar)
                    .addComponent(lbInstruccionesModificar)
                    .addComponent(lbInstruccionesVer)
                    .addComponent(lbInstruccionesEliminar))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAP)
                            .addComponent(lbPeso)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbkg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAM)
                            .addComponent(lbAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcm))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSexo)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbContrasena)
                            .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbPCA)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("Pacientes");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ver");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estadística");

        jMenuItem5.setText("Ver");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Notificaciones");

        jMenuItem6.setText("Enviar");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1665, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        lbTituloAgregar.setVisible(true);
        lbInstruccionesAgregar.setVisible(true);
        lbNombre.setVisible(true);
        lbAP.setVisible(true);
        lbAM.setVisible(true);
        lbSexo.setVisible(true);
        lbEdad.setVisible(true);
        lbPeso.setVisible(true);
        lbkg.setVisible(true);
        lbAltura.setVisible(true);
        lbcm.setVisible(true);
        lbUsuario.setVisible(true);
        lbContrasena.setVisible(true);
        txtNombre.setVisible(true);
        txtAP.setVisible(true);
        txtAM.setVisible(true);
        cmbSexo.setVisible(true);
        txtEdad.setVisible(true);
        txtPeso.setVisible(true);
        txtAltura.setVisible(true);
        txtUsuario.setVisible(true);
        pswContrasena.setVisible(true);
        btnAgregar.setVisible(true);
        btnCancelar.setVisible(true);
        //
        lbTituloModificar.setVisible(false);
        lbInstruccionesModificar.setVisible(false);
        btnGuardar.setVisible(false);
        //
        lbTituloVer.setVisible(false);
        lbInstruccionesVer.setVisible(false);
        btnBuscar.setVisible(false);
        //
        lbTituloEliminar.setVisible(false);
        lbInstruccionesEliminar.setVisible(false);
        btnEliminar.setVisible(false);
        //
        lbPCA.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        lbTituloAgregar.setVisible(false);
        lbInstruccionesAgregar.setVisible(false);
        lbNombre.setVisible(true);
        lbAP.setVisible(true);
        lbAM.setVisible(true);
        lbSexo.setVisible(true);
        lbEdad.setVisible(true);
        lbPeso.setVisible(true);
        lbkg.setVisible(true);
        lbAltura.setVisible(true);
        lbcm.setVisible(true);
        lbUsuario.setVisible(true);
        lbContrasena.setVisible(true);
        txtNombre.setVisible(true);
        txtAP.setVisible(true);
        txtAM.setVisible(true);
        cmbSexo.setVisible(true);
        txtEdad.setVisible(true);
        txtPeso.setVisible(true);
        txtAltura.setVisible(true);
        txtUsuario.setVisible(true);
        pswContrasena.setVisible(true);
        btnAgregar.setVisible(false);
        btnCancelar.setVisible(true);
        //
        lbTituloModificar.setVisible(true);
        lbInstruccionesModificar.setVisible(true);
        btnGuardar.setVisible(true);
        //
        lbTituloVer.setVisible(false);
        lbInstruccionesVer.setVisible(false);
        btnBuscar.setVisible(true);
        //
        lbTituloEliminar.setVisible(false);
        lbInstruccionesEliminar.setVisible(false);
        btnEliminar.setVisible(false);
        //
        lbPCA.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        lbTituloAgregar.setVisible(false);
        lbInstruccionesAgregar.setVisible(false);
        lbNombre.setVisible(true);
        lbAP.setVisible(true);
        lbAM.setVisible(true);
        lbSexo.setVisible(false);
        lbEdad.setVisible(true);
        lbPeso.setVisible(true);
        lbkg.setVisible(true);
        lbAltura.setVisible(true);
        lbcm.setVisible(true);
        lbUsuario.setVisible(true);
        lbContrasena.setVisible(false);
        txtNombre.setVisible(true);
        txtAP.setVisible(true);
        txtAM.setVisible(true);
        cmbSexo.setVisible(false);
        txtEdad.setVisible(true);
        txtPeso.setVisible(true);
        txtAltura.setVisible(true);
        txtUsuario.setVisible(true);
        pswContrasena.setVisible(false);
        btnAgregar.setVisible(false);
        btnCancelar.setVisible(true);
        //
        lbTituloModificar.setVisible(false);
        lbInstruccionesModificar.setVisible(false);
        btnGuardar.setVisible(false);
        //
        lbTituloVer.setVisible(true);
        lbInstruccionesVer.setVisible(true);
        btnBuscar.setVisible(true);
        //
        lbTituloEliminar.setVisible(false);
        lbInstruccionesEliminar.setVisible(false);
        btnEliminar.setVisible(false);
        //
        lbPCA.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        lbTituloAgregar.setVisible(false);
        lbInstruccionesAgregar.setVisible(false);
        lbNombre.setVisible(true);
        lbAP.setVisible(true);
        lbAM.setVisible(true);
        lbSexo.setVisible(false);
        lbEdad.setVisible(false);
        lbPeso.setVisible(false);
        lbkg.setVisible(false);
        lbAltura.setVisible(false);
        lbcm.setVisible(false);
        lbUsuario.setVisible(true);
        lbContrasena.setVisible(false);
        txtNombre.setVisible(true);
        txtAP.setVisible(true);
        txtAM.setVisible(true);
        cmbSexo.setVisible(false);
        txtEdad.setVisible(false);
        txtPeso.setVisible(false);
        txtAltura.setVisible(false);
        txtUsuario.setVisible(true);
        pswContrasena.setVisible(false);
        btnAgregar.setVisible(false);
        btnCancelar.setVisible(true);
        //
        lbTituloModificar.setVisible(false);
        lbInstruccionesModificar.setVisible(false);
        btnGuardar.setVisible(false);
        //
        lbTituloVer.setVisible(false);
        lbInstruccionesVer.setVisible(false);
        btnBuscar.setVisible(true);
        //
        lbTituloEliminar.setVisible(true);
        lbInstruccionesEliminar.setVisible(true);
        btnEliminar.setVisible(true);
        //
        lbPCA.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //Funcion agregar
        lbTituloAgregar.setVisible(false);
        lbInstruccionesAgregar.setVisible(false);
        lbNombre.setVisible(false);
        lbAP.setVisible(false);
        lbAM.setVisible(false);
        lbSexo.setVisible(false);
        lbEdad.setVisible(false);
        lbPeso.setVisible(false);
        lbkg.setVisible(false);
        lbAltura.setVisible(false);
        lbcm.setVisible(false);
        lbUsuario.setVisible(false);
        lbContrasena.setVisible(false);
        txtNombre.setVisible(false);
        txtAP.setVisible(false);
        txtAM.setVisible(false);
        cmbSexo.setVisible(false);
        txtEdad.setVisible(false);
        txtPeso.setVisible(false);
        txtAltura.setVisible(false);
        txtUsuario.setVisible(false);
        pswContrasena.setVisible(false);
        btnAgregar.setVisible(false);
        btnCancelar.setVisible(false);
        //Funcion Modificar
        lbTituloModificar.setVisible(false);
        lbInstruccionesModificar.setVisible(false);
        btnGuardar.setVisible(false);
        //Funcion Ver
        lbTituloVer.setVisible(false);
        lbInstruccionesVer.setVisible(false);
        btnBuscar.setVisible(false);
        //Funcion Eliminar
        lbTituloEliminar.setVisible(false);
        lbInstruccionesEliminar.setVisible(false);
        btnEliminar.setVisible(false);
        //ACP
        lbPCA.setVisible(true);
        //Ejecutar script de Python desde cmd
        ProcessBuilder pb = new ProcessBuilder("cmd.exe", "/c", "cd \"C:\\Users\\aleja\\Documents\\UPIITA\\Proyecto_Terminal\\PT_I\" && \"C:\\Users\\aleja\\Anaconda3\\python.exe\" \"ACP_PT.py\"");
        pb.redirectErrorStream(true);
        Process p = null;
        try {
            p = pb.start();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream()));
        String line = null;
        while (true) {
            try {
                line = r.readLine();
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        if (line == null) { break; }
        System.out.println(line);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAM;
    private javax.swing.JLabel lbAP;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbInstruccionesAgregar;
    private javax.swing.JLabel lbInstruccionesEliminar;
    private javax.swing.JLabel lbInstruccionesModificar;
    private javax.swing.JLabel lbInstruccionesVer;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPCA;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTituloAgregar;
    private javax.swing.JLabel lbTituloEliminar;
    private javax.swing.JLabel lbTituloModificar;
    private javax.swing.JLabel lbTituloVer;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbcm;
    private javax.swing.JLabel lbkg;
    private javax.swing.JPasswordField pswContrasena;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
