/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutriologo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ale
 */
public class Paciente extends javax.swing.JFrame {
    Connection connection;
    PreparedStatement preparedStatement;
    ResultSet resultSet;
    ResultSetMetaData rsm;
    DefaultTableModel dtm;

    public Paciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanelAgregarPaciente.setVisible(false);
        jPanelModificarPaciente.setVisible(false);
        jPanelVerPacientes.setVisible(false);
        jPanelEliminarPaciente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAgregarPaciente = new javax.swing.JPanel();
        lbTituloAgregar = new javax.swing.JLabel();
        lbInstruccionesAgregar = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbAP = new javax.swing.JLabel();
        lbAM = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        lbcm = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        lbkg = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        lbCintura = new javax.swing.JLabel();
        lbCadera = new javax.swing.JLabel();
        lbTAS = new javax.swing.JLabel();
        lbTAD = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        txtAM = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCintura = new javax.swing.JTextField();
        txtCadera = new javax.swing.JTextField();
        txtTAS = new javax.swing.JTextField();
        txtTAD = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        pswContrasena = new javax.swing.JPasswordField();
        btnAgregar = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();
        btnSalirA = new javax.swing.JButton();
        lbcm1 = new javax.swing.JLabel();
        lbcm2 = new javax.swing.JLabel();
        jPanelModificarPaciente = new javax.swing.JPanel();
        lbInstruccionesModificar = new javax.swing.JLabel();
        lbTituloModificar = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbAP1 = new javax.swing.JLabel();
        lbAM1 = new javax.swing.JLabel();
        lbSexo1 = new javax.swing.JLabel();
        lbAltura1 = new javax.swing.JLabel();
        lbcm3 = new javax.swing.JLabel();
        lbPeso1 = new javax.swing.JLabel();
        lbkg1 = new javax.swing.JLabel();
        lbEdad1 = new javax.swing.JLabel();
        lbCintura1 = new javax.swing.JLabel();
        lbcm4 = new javax.swing.JLabel();
        lbCadera1 = new javax.swing.JLabel();
        lbcm5 = new javax.swing.JLabel();
        lbTAS1 = new javax.swing.JLabel();
        lbTAD1 = new javax.swing.JLabel();
        lbUsuario1 = new javax.swing.JLabel();
        lbContrasena1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtAP1 = new javax.swing.JTextField();
        txtAM1 = new javax.swing.JTextField();
        cmbSexo1 = new javax.swing.JComboBox();
        txtAltura1 = new javax.swing.JTextField();
        txtPeso1 = new javax.swing.JTextField();
        txtEdad1 = new javax.swing.JTextField();
        txtCintura1 = new javax.swing.JTextField();
        txtCadera1 = new javax.swing.JTextField();
        txtTAS1 = new javax.swing.JTextField();
        txtTAD1 = new javax.swing.JTextField();
        txtUsuario1 = new javax.swing.JTextField();
        pswContrasena1 = new javax.swing.JPasswordField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalirM = new javax.swing.JButton();
        btnCancelarM = new javax.swing.JButton();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanelVerPacientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbInstruccionesVer = new javax.swing.JLabel();
        lbTituloVer = new javax.swing.JLabel();
        btnSalirVerPacientes = new javax.swing.JButton();
        btnCancelarV = new javax.swing.JButton();
        jPanelEliminarPaciente = new javax.swing.JPanel();
        lbTituloEliminar = new javax.swing.JLabel();
        lbInstruccionesEliminar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnSalirEliminarPaciente = new javax.swing.JButton();
        btnCancelarE = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanelAgregarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAgregarPaciente.setAlignmentX(0.0F);
        jPanelAgregarPaciente.setAlignmentY(0.0F);
        jPanelAgregarPaciente.setMaximumSize(new java.awt.Dimension(1600, 900));
        jPanelAgregarPaciente.setPreferredSize(new java.awt.Dimension(1600, 900));

        lbTituloAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTituloAgregar.setText("Agregar un nuevo paciente");

        lbInstruccionesAgregar.setText("Ingrese los datos solicitados y presione el botón 'Agregar'.");

        lbNombre.setText("Nombre:");

        lbAP.setText("Apellido paterno:");

        lbAM.setText("Apellido materno:");

        lbSexo.setText("Sexo:");

        lbAltura.setText("Altura:");

        lbcm.setText("cm");

        lbPeso.setText("Peso:");

        lbkg.setText("kg");

        lbEdad.setText("Edad:");

        lbCintura.setText("Cintura:");

        lbCadera.setText("Cadera:");

        lbTAS.setText("TAS:");

        lbTAD.setText("TAD:");

        lbUsuario.setText("Usuario:");

        lbContrasena.setText("Contraseña:");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelarA.setText("Cancelar");
        btnCancelarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAActionPerformed(evt);
            }
        });

        btnSalirA.setText("Salir");
        btnSalirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAActionPerformed(evt);
            }
        });

        lbcm1.setText("cm");

        lbcm2.setText("cm");

        javax.swing.GroupLayout jPanelAgregarPacienteLayout = new javax.swing.GroupLayout(jPanelAgregarPaciente);
        jPanelAgregarPaciente.setLayout(jPanelAgregarPacienteLayout);
        jPanelAgregarPacienteLayout.setHorizontalGroup(
            jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloAgregar)
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbInstruccionesAgregar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbCintura)
                                .addGap(18, 18, 18)
                                .addComponent(txtCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbcm1))
                            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                                .addComponent(lbCadera)
                                .addGap(18, 18, 18)
                                .addComponent(txtCadera, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbcm2)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTAD)
                            .addComponent(lbTAS))
                        .addGap(25, 25, 25)
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTAD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                                .addComponent(lbAP)
                                .addGap(54, 54, 54)
                                .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAM)
                                    .addComponent(lbSexo))
                                .addGap(50, 50, 50)
                                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeso)
                            .addComponent(lbAltura)
                            .addComponent(lbEdad))))
                .addGap(26, 26, 26)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEdad)
                    .addComponent(txtPeso)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbkg)
                    .addComponent(lbcm))
                .addGap(137, 137, 137)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addComponent(lbUsuario)
                        .addGap(31, 31, 31)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addComponent(lbContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addComponent(btnSalirA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCancelarA)
                .addGap(901, 901, 901))
        );
        jPanelAgregarPacienteLayout.setVerticalGroup(
            jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                .addComponent(lbTituloAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInstruccionesAgregar)
                .addGap(55, 55, 55)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAP)
                    .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbkg))
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAM)
                            .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAltura)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcm)))
                    .addGroup(jPanelAgregarPacienteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbContrasena)
                            .addComponent(pswContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexo))
                .addGap(31, 31, 31)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTAS)
                    .addComponent(txtTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCintura)
                    .addComponent(lbcm1))
                .addGap(18, 18, 18)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadera)
                    .addComponent(txtCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTAD)
                    .addComponent(txtTAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcm2))
                .addGap(57, 57, 57)
                .addGroup(jPanelAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirA)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelarA))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        lbInstruccionesModificar.setText("Busque al paciente por su nombre o apellidos, luego actualice los datos y presione el botón 'Guardar'.");

        lbTituloModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTituloModificar.setText("Modificar paciente");

        lbNombre1.setText("Nombre:");

        lbAP1.setText("Apellido paterno:");

        lbAM1.setText("Apellido materno:");

        lbSexo1.setText("Sexo:");

        lbAltura1.setText("Altura:");

        lbcm3.setText("cm");

        lbPeso1.setText("Peso:");

        lbkg1.setText("kg");

        lbEdad1.setText("Edad:");

        lbCintura1.setText("Cintura:");

        lbcm4.setText("cm");

        lbCadera1.setText("Cadera:");

        lbcm5.setText("cm");

        lbTAS1.setText("TAS:");

        lbTAD1.setText("TAD:");

        lbUsuario1.setText("Usuario:");

        lbContrasena1.setText("Contraseña:");

        cmbSexo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");

        btnSalirM.setText("Salir");
        btnSalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMActionPerformed(evt);
            }
        });

        btnCancelarM.setText("Cancelar");
        btnCancelarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMActionPerformed(evt);
            }
        });

        lbID.setText("ID:");

        javax.swing.GroupLayout jPanelModificarPacienteLayout = new javax.swing.GroupLayout(jPanelModificarPaciente);
        jPanelModificarPaciente.setLayout(jPanelModificarPacienteLayout);
        jPanelModificarPacienteLayout.setHorizontalGroup(
            jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbContrasena1)
                .addGap(1499, 1499, 1499))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCintura1)
                                    .addComponent(lbUsuario1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pswContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                        .addComponent(txtCintura1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbcm4)
                                        .addGap(208, 208, 208)
                                        .addComponent(txtCadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbcm5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSexo1)
                                    .addComponent(lbID))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbCadera1)
                                                .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                    .addComponent(cmbSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(165, 165, 165)
                                                    .addComponent(lbAltura1)))
                                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(lbAP1)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                        .addComponent(txtAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(76, 76, 76)
                                                        .addComponent(lbAM1))
                                                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                        .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbcm3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbPeso1)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAM1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtTAS1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                            .addComponent(txtPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lbkg1))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                                .addGap(296, 296, 296)
                                                .addComponent(lbTAS1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEdad1)
                            .addComponent(lbTAD1))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTAD1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addComponent(btnSalirM, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnCancelarM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addComponent(lbTituloModificar)
                                .addGap(27, 27, 27)
                                .addComponent(lbInstruccionesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );
        jPanelModificarPacienteLayout.setVerticalGroup(
            jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbTituloModificar)
                                    .addComponent(lbInstruccionesModificar))
                                .addGap(47, 47, 47)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbID)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNombre1)
                                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbAP1)))
                            .addComponent(txtAP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbAM1)
                                .addComponent(txtAM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbAltura1)
                                    .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPeso1)
                                    .addComponent(txtPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbkg1)
                                    .addComponent(lbcm3)
                                    .addComponent(lbEdad1)
                                    .addComponent(txtEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelModificarPacienteLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbSexo1)
                                    .addComponent(cmbSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57)
                        .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTAS1)
                            .addComponent(lbCintura1)
                            .addComponent(lbcm4)
                            .addComponent(txtCintura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCadera1)
                            .addComponent(txtCadera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcm5)
                            .addComponent(txtTAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTAD1)
                            .addComponent(txtTAD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(lbUsuario1))
                    .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasena1)
                    .addComponent(pswContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalirM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModificarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido P", "Apellido M", "Sexo", "Altura", "Peso", "Edad", "IMC", "ICC", "TAS", "TAD", "Usuario", "Contrasena"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbInstruccionesVer.setText("En la siguiente tabla puede ver los pacientes registrados en la base de datos.");

        lbTituloVer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTituloVer.setText("Ver paciente");

        btnSalirVerPacientes.setText("Salir");
        btnSalirVerPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVerPacientesActionPerformed(evt);
            }
        });

        btnCancelarV.setText("Cancelar");
        btnCancelarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerPacientesLayout = new javax.swing.GroupLayout(jPanelVerPacientes);
        jPanelVerPacientes.setLayout(jPanelVerPacientesLayout);
        jPanelVerPacientesLayout.setHorizontalGroup(
            jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPacientesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbTituloVer)
                .addGap(18, 18, 18)
                .addComponent(lbInstruccionesVer, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(996, Short.MAX_VALUE))
            .addGroup(jPanelVerPacientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnSalirVerPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVerPacientesLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jPanelVerPacientesLayout.setVerticalGroup(
            jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPacientesLayout.createSequentialGroup()
                .addGroup(jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInstruccionesVer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTituloVer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 711, Short.MAX_VALUE)
                .addGroup(jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirVerPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(jPanelVerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVerPacientesLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        lbTituloEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTituloEliminar.setText("Eliminar paciente");

        lbInstruccionesEliminar.setText("Busque por el ID al paciente y presione el botón 'Eliminar'.");

        btnEliminar.setText("Eliminar");

        btnSalirEliminarPaciente.setText("Salir");
        btnSalirEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEliminarPacienteActionPerformed(evt);
            }
        });

        btnCancelarE.setText("Cancelar");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarPacienteLayout = new javax.swing.GroupLayout(jPanelEliminarPaciente);
        jPanelEliminarPaciente.setLayout(jPanelEliminarPacienteLayout);
        jPanelEliminarPacienteLayout.setHorizontalGroup(
            jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                .addComponent(lbTituloEliminar)
                .addGap(34, 34, 34)
                .addComponent(lbInstruccionesEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalirEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 917, Short.MAX_VALUE)
                .addComponent(btnCancelarE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        jPanelEliminarPacienteLayout.setVerticalGroup(
            jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarPacienteLayout.createSequentialGroup()
                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloEliminar)
                    .addComponent(lbInstruccionesEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, Short.MAX_VALUE)
                .addGroup(jPanelEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jMenu1.setText("Pacientes");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ver");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Eliminar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Estadística");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenuItem5.setText("Ver");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Notificaciones");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });

        jMenuItem6.setText("Enviar");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelVerPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelVerPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        jPanelAgregarPaciente.getAccessibleContext().setAccessibleParent(jPanelAgregarPaciente);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Agregar paciente
        jPanelAgregarPaciente.setVisible(true);
        jPanelModificarPaciente.setVisible(false);
        jPanelVerPacientes.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Modificar paciente
        jPanelModificarPaciente.setVisible(true);
        jPanelAgregarPaciente.setVisible(false);
        jPanelVerPacientes.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //Ver pacientes
        jPanelVerPacientes.setVisible(true);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
        try{
            connection = Conexion.getConnection();
            preparedStatement = connection.prepareStatement("SELECT * FROM paciente ORDER BY Apellido_P;");
            resultSet = preparedStatement.executeQuery();
            rsm = resultSet.getMetaData();
            ArrayList<Object[]> data = new ArrayList<>();
            while(resultSet.next()){
                Object [] rows = new Object[rsm.getColumnCount()];
                for(int i=0; i < rows.length; i++){
                    rows[i] = resultSet.getObject(i+1);
                }
                data.add(rows);
            }
            dtm = (DefaultTableModel)this.jTable1.getModel();
            for(int i=0; i < data.size(); i++){
                dtm.addRow(data.get(i));
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //Eliminar paciente
        try{
            connection = Conexion.getConnection();
            preparedStatement = connection.prepareStatement("DELETE FROM paciente WHERE ID_Paciente = ?");
            int id = Integer.parseInt(txtID.getText());
            preparedStatement.setInt(1, id);
            resultSet = preparedStatement.executeQuery();
            rsm = resultSet.getMetaData();
            connection.close();
        } catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnCancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAActionPerformed
        //Index
        this.setVisible(false);
        Index i0 = new Index();
        i0.show();
    }//GEN-LAST:event_btnCancelarAActionPerformed

    private void btnSalirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirAActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Botón BUSCAR (Modificar y Eliminar)
        String tipo = null;
        if(cmbSexo.getSelectedIndex()== 1)
        tipo = "Masculino";
        else
        tipo = "Femenino";
        try{
            connection = Conexion.getConnection();
            preparedStatement = connection.prepareStatement("SELECT Nombre, Apellido_P, Apellido_M, Altura, Peso, Edad," +
                "TAS, TAD, Usuario" +
                "FROM paciente WHERE ID_Paciente = ?");
            int id = Integer.parseInt(txtID.getText());
            preparedStatement.setInt(1, id);
            preparedStatement.setString(2, txtNombre.getText());
            preparedStatement.setString(3, txtAP.getText());
            preparedStatement.setString(4, txtAM.getText());
            resultSet = preparedStatement.executeQuery();
            rsm = resultSet.getMetaData();
            connection.close();
        } catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirVerPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVerPacientesActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirVerPacientesActionPerformed

    private void btnCancelarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVActionPerformed
        this.setVisible(false);
        Index i0 = new Index();
        i0.show();
    }//GEN-LAST:event_btnCancelarVActionPerformed

    private void btnSalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirMActionPerformed

    private void btnCancelarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMActionPerformed
        // Index
        this.setVisible(false);
        Index i0 = new Index();
        i0.show();
    }//GEN-LAST:event_btnCancelarMActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Agregar nuevo paciente
        String  tipo = null;
        if(cmbSexo.getSelectedIndex()== 1)
                tipo = "Masculino";
        else
            tipo = "Femenino";
        try{
            connection = Conexion.getConnection();
            preparedStatement = connection.prepareStatement("INSERT INTO paciente (ID_Paciente, Nombre, Apellido_P, "
                    + "Apellido_M, Sexo, Altura, Peso, Edad, IMC, ICC, TAS, TAD, Usuario, Contrasena)"
                + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            preparedStatement.setString(1, null);
            preparedStatement.setString(2, txtNombre.getText());
            preparedStatement.setString(3, txtAP.getText());
            preparedStatement.setString(4, txtAM.getText());
            preparedStatement.setString(5, tipo);
            preparedStatement.setString(6, txtAltura.getText());
            preparedStatement.setString(7, txtPeso.getText());
            float IMC = 0;  //Peso[kg]/(Altura[m])^2
            float a = Float.parseFloat(txtAltura.getText());
            float p = Float.parseFloat(txtPeso.getText());
            IMC = p/((a/100)*(a/100));
            preparedStatement.setString(8, txtEdad.getText());
            preparedStatement.setFloat(9, IMC);
            float ICC = 0;  //Peso[kg]/(Altura[m])^2
            float ci = Float.parseFloat(txtCintura.getText());
            float ca = Float.parseFloat(txtCadera.getText());
            ICC = ci/ca;
            preparedStatement.setFloat(10, ICC);
            preparedStatement.setString(11, txtTAS.getText());
            preparedStatement.setString(12, txtTAD.getText());
            preparedStatement.setString(13, txtUsuario.getText());
            preparedStatement.setString(14, pswContrasena.getText());
            int res = preparedStatement.executeUpdate();
            if (res > 0){
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Paciente guardado");
                Index i0 = new Index();
                i0.show();
            } else{
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
            connection.close();
        } catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        //NOTIFICACIONES
        this.setVisible(false);
        Notificaciones n0 = new Notificaciones();
        n0.show();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // Estadistica
        this.setVisible(false);
        Estadistica e0 = new Estadistica();
        e0.show();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnSalirEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEliminarPacienteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirEliminarPacienteActionPerformed

    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        // Index
        this.setVisible(false);
        Index i0 = new Index();
        i0.show();
    }//GEN-LAST:event_btnCancelarEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        txtID.setText(model.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarA;
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnCancelarM;
    private javax.swing.JButton btnCancelarV;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalirA;
    private javax.swing.JButton btnSalirEliminarPaciente;
    private javax.swing.JButton btnSalirM;
    private javax.swing.JButton btnSalirVerPacientes;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbSexo1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanelAgregarPaciente;
    private javax.swing.JPanel jPanelEliminarPaciente;
    private javax.swing.JPanel jPanelModificarPaciente;
    private javax.swing.JPanel jPanelVerPacientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAM;
    private javax.swing.JLabel lbAM1;
    private javax.swing.JLabel lbAP;
    private javax.swing.JLabel lbAP1;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbAltura1;
    private javax.swing.JLabel lbCadera;
    private javax.swing.JLabel lbCadera1;
    private javax.swing.JLabel lbCintura;
    private javax.swing.JLabel lbCintura1;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbContrasena1;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbEdad1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbInstruccionesAgregar;
    private javax.swing.JLabel lbInstruccionesEliminar;
    private javax.swing.JLabel lbInstruccionesModificar;
    private javax.swing.JLabel lbInstruccionesVer;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbPeso1;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbSexo1;
    private javax.swing.JLabel lbTAD;
    private javax.swing.JLabel lbTAD1;
    private javax.swing.JLabel lbTAS;
    private javax.swing.JLabel lbTAS1;
    private javax.swing.JLabel lbTituloAgregar;
    private javax.swing.JLabel lbTituloEliminar;
    private javax.swing.JLabel lbTituloModificar;
    private javax.swing.JLabel lbTituloVer;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuario1;
    private javax.swing.JLabel lbcm;
    private javax.swing.JLabel lbcm1;
    private javax.swing.JLabel lbcm2;
    private javax.swing.JLabel lbcm3;
    private javax.swing.JLabel lbcm4;
    private javax.swing.JLabel lbcm5;
    private javax.swing.JLabel lbkg;
    private javax.swing.JLabel lbkg1;
    private javax.swing.JPasswordField pswContrasena;
    private javax.swing.JPasswordField pswContrasena1;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAM1;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtAP1;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAltura1;
    private javax.swing.JTextField txtCadera;
    private javax.swing.JTextField txtCadera1;
    private javax.swing.JTextField txtCintura;
    private javax.swing.JTextField txtCintura1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPeso1;
    private javax.swing.JTextField txtTAD;
    private javax.swing.JTextField txtTAD1;
    private javax.swing.JTextField txtTAS;
    private javax.swing.JTextField txtTAS1;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
